name: CI/CD Pipeline

on:
  workflow_dispatch: # Enables manual trigger via GitHub Actions UI
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

env:
  AWS_REGION: "us-east-1"
  EKS_CLUSTER_NAME: "my-eks-cluster"

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Validate Terraform configuration
    - name: Terraform Validate
      run: terraform validate

    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan

    # Terraform Apply
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve

  application:
    name: Application Deployment
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Setup kubectl
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.3'

    # Authenticate with EKS cluster
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    # Deploy to Kubernetes
    - name: Deploy Application
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
